# Copyright 2024 D-Wave
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from datetime import datetime
import pytest

CUR_DIR = os.path.dirname(os.path.realpath(__file__))

from src.structures.block import Block
from src.utilities.crypto_utils import calculate_hash

NUM_BLOCKS = 5
blocks = []
hash_seed = "a1b2c3e4f5"
owner_keysets = []
transactions = []


def test_creation():
    """Partly intended to test basic initialization and locking behavior for Block class,
    partly just to create Block objects to support later tests. Only one explicit assert, but
    Block class has internal validation logic that will throw errors if parts of the
    initialization aren't working properly.

    Input:
        transaction_gen: fixture for SingleSourceTransactionGenerator object (see data_generation folder), which
                         will generate Transaction objects with which to create the Blocks.

    Expected Output:
        blocks: list of Block objects (length defined by NUM_BLOCKs), properly initialized, each with
                one more transaction than the previous, as generated by the fixture"""

    timestamps = []
    for i in range(1, NUM_BLOCKS + 1):
        nonce = i
        if len(blocks) > 0:
            prev_hash = blocks[-1].previous_hash
        else:
            prev_hash = ""
        if i%2 == 0:
            next_timestamp = datetime.timestamp(datetime.now())
            timestamps.append(next_timestamp)
            new_block = Block(
                miner_id="test_miner",
                previous_block_hash=prev_hash,
                nonce=nonce,
                timestamp=next_timestamp
            )
        else:
            new_block = Block(
                miner_id="test_miner",
                previous_block_hash=prev_hash,
                nonce=nonce,
            )
            default_timestamp = new_block.timestamp
            timestamps.append(default_timestamp)
        lock_fails = []
        try:
            new_block.lock()
            lock_fails.append(1)
        except:
            pass

        # don't need an actual quantum hash for tests, a SHA256 over a short string will do fine
        quantum_hash = calculate_hash(hash_seed[: min(i, len(hash_seed))])

        new_block.set_quantum_hash(quantum_hash)

        try:
            new_block.lock()
            lock_fails.append(2)
        except:
            pass

        assert len(lock_fails) == 0, f"Block with previous hash {new_block.previous_hash} allowed\
                                     improper locking at steps {lock_fails}"

        new_block.set_hash()
        new_block.lock()
        assert new_block.locked, f"Block {i} did not lock properly."
        assert new_block.quantum_hash == quantum_hash, f"Quantum hash for block {i} was \
                                                {new_block.quantum_hash} expected {quantum_hash}"
        blocks.append(new_block)

    assert len(blocks) == NUM_BLOCKS, f"Wrong number of blocks. Expected \
                                         {NUM_BLOCKS}, received {len(blocks)}"
    
    for i in range(len(timestamps)-1):
        assert timestamps[i] < timestamps[i+1], f"Timestamp {i} with value {timestamps[i]} and \
                                        timestamp {i+1} with value {timestamps[i+1]} out of order."


def test_validation():
    for idx, block in enumerate(blocks):
        assert block.validate_hash(), f"Block {idx+1} failed to validate its hash."
        assert block.current_quantum_hash, f"Block {idx+1} is missing quantum hash."
        assert block.current_block_hash, f"Block {idx+1} is missing block hash"


def test_data_protection():
    """This function tests the data protection functionality of Block, specifically checking that 
    certain operations properly strip away previously-set quantum hashes and prevent the block hash
    from being set until a current quantum hash is added back."""

    for i in range(NUM_BLOCKS):
        nonce = 2 * NUM_BLOCKS - i

        if len(blocks) > 0:
            prev_hash = blocks[-1].previous_hash
        else:
            prev_hash = ""

        new_block = Block(miner_id="test_miner",previous_block_hash=prev_hash, nonce=nonce)
        quantum_hash = calculate_hash(hash_seed[: -min(i, len(hash_seed) - 1)])
        new_block.set_quantum_hash(quantum_hash)

        assert new_block.current_quantum_hash, f"On check 1, Block {i+1} lacked quantum hash."

        try:
            new_block.set_hash()
            assert False, f"On check 1, Block {i+1} set block hash without current quantum hash."
        except:
            pass

        quantum_hash = calculate_hash(quantum_hash)
        new_block.set_quantum_hash(quantum_hash)
        assert new_block.current_quantum_hash, f"On check 2, block {i+1} lacked quantum hash."
        new_block.nonce += 1
        assert new_block.current_quantum_hash == False
        try:
            new_block.set_hash()
            assert False, f"On check 2, block {i+1} set block hash without current quantum hash."
        except:
            pass

        quantum_hash = calculate_hash(quantum_hash)
        new_block.set_quantum_hash(quantum_hash)
        new_block.set_hash()
        assert new_block.current_block_hash, f"Block {i+1} lacked current hash after it was set."
        new_block.lock()
        assert new_block.locked, f"Block {i+1} didn't lock properly."


def test_io(tmpdir):
    """This function tests the serialization and deserialization functions of Block. The from_json
    method includes a check almost identical to the final assert which raises an Exception if it
    fails, so unless something has gone very wrong, the test should either pass or stop executing
    before the assert has a chance to fail. Either way, the hash calculation requires every single
    bit in the original block and saved block to be identical, so any logic errors in Block's data
    handling should break this test--if it starts failing, more precise tests can be written to
    track down the problems.

    Input:
        blocks: list of Block objects created by previous test
    Expected Output:
        received_block: for each Block in blocks, received_block should be assigned
                        an exact copy of that block by writing to and then reading back
                        the block data from a file (created in its own temporary directory
                        by the tmpdir fixture). Each received block should exactly match
                        its original block in type and hash."""

    block_files = []
    for idx, block in enumerate(blocks):
        tempfile = tmpdir.mkdir(f"blockdir{idx}").join(f"block{idx}.txt")
        block_files.append(tempfile)
        block_data = block.to_json
        with open(tempfile, "w") as f:
            f.write(block_data)

    for i in range(len(block_files)):
        with open(block_files[i], "r") as f:
            received_block_data = f.read()
        received_block = Block.from_json(received_block_data)
        assert blocks[i] == received_block, "Received block and written block don't match"
