import math
import os
import random
import sys

sys.path.append(os.path.join("..", ".."))

from src.structures.block_score_tree import BlockNode, BlockScoreTree


def dummy_hash(num: int):
    """Returns a three-character string in a set sequence (depending only on the input number), of the form
    A0a and cylcing through all possible triples of that form (Capital Letter/digit/lowercase letter), for
    a total of 6760 possible 'hash' values. This guarantees several thousand unique values while keeping them
    short and well-ordered so to be convenient to read for debugging purposes. Will start to cause errors
    if a tree of size 6761 or larger is tested (as hashes will repeat)."""

    cap_block = [i for i in range(65, 91)]
    digit_block = [i for i in range(48, 58)]
    lower_block = [i for i in range(97, 123)]
    return (
        chr(cap_block[num % 26])
        + chr(digit_block[((num + 1) // 26) % 10])
        + chr(lower_block[((num + 2) // 260) % 26])
    )


def generate_simple_tree_dicts(
    num_nodes: int = 256, num_primary_branches: int = 8, max_depth: int = 3
):
    """Generates data for a tree with a simple branching structure: each branch has exactly one child branch, up
    to the limit defined by the max_depth parameter. Each child has half as many blocks as its parent.
    If the number of blocks allocated exceeds num_nodes because of rounding issues or if the depth
    is high enough that new branches would have 0 blocks, algorithm will stop prematurely, returning
    the tree generated thus far. Branch placement on the parent branch is random."""

    trunk_length = num_nodes // 2
    blocks_remaining = num_nodes - trunk_length
    primary_branch_blocks = blocks_remaining // 2
    primary_branch_length = primary_branch_blocks // num_primary_branches
    tree_data = [{"length": trunk_length}]

    for depth in range(max_depth):
        for branch_num in range(1, num_primary_branches + 1):
            length = primary_branch_length // (2**depth)
            if length == 0 or blocks_remaining < length:
                break
            parent = depth * num_primary_branches + max(depth, 1) * branch_num
            if length > 1:
                root = random.randint(1, 2 * length - 2)
            else:
                root = 1
            tree_data.append({"parent": parent, "root": root, "length": length})
            blocks_remaining -= length

    return tree_data


def generate_binary_layered_tree_dicts(prim_branches: int = 4, num_layers: int = 5):
    """Generates data for a tree with a trunk and a set number of primary branches. Each primary
    branch and later will have exactly two branches, each with half the number of
    blocks of the previous layer, up to num_layers total branches (including the trunk).
    Branch size is chosen so that the bottom-level branches have exactly 2 blocks."""

    tree_data = []
    prim_branches = 4
    num_layers = 5
    primary_branch_length = 2**num_layers
    tree_data.append({"length": 2 * primary_branch_length})
    for j in range(prim_branches):
        root = random.randint(0, 2 * primary_branch_length - 2)
        tree_data.append({"parent": 0, "root": root, "length": primary_branch_length})

    for i in range(1, num_layers):
        length = primary_branch_length // (2**i)
        for j in range(
            prim_branches * (2 ** (i - 1)) - prim_branches + 1,
            prim_branches * (2**i) - prim_branches + 1,
        ):
            parent = j
            for k in range(2):
                root = random.randint(0, 2 * length - 2)
                tree_data.append({"parent": parent, "root": root, "length": length})

    return tree_data


def append_scores(
    tree_dict, low_score_prob: float = 0.3, high_score: float = 1.0, low_score: float = -1.0
):
    """Adds randomized scores to the dictionaries generated by the dictionary generation functions."""

    for dict in tree_dict[1:]:
        scores = []
        for i in range(dict["length"]):
            score_roll = random.randint(1, 1000)
            if score_roll <= int(low_score_prob * 1000):
                score = low_score
            else:
                score = high_score
            scores.append(score)
        dict.update({"score": scores})

    return tree_dict


def generate_tree_from_dicts(tree_dicts):
    """Generates a BlockScoreTree object from a dictionary list generated by one of the dictionary-generation functions.
    Adds blocks in a random order, but only to branches of the tree that are 'active' in the sense that their parent
    branch exists and has been extended at least one block past their root block."""

    for i in range(len(tree_dicts)):
        tree_dicts[i].update({"branch number": i})

    tree = BlockScoreTree()
    num_nodes = 1
    genesis_hash = dummy_hash(num_nodes)
    tree.add_block(genesis_hash, None, 1)
    trunk_dict = tree_dicts[0]
    trunk_dict.update({"branch": tree.trunk})
    active_branches = [trunk_dict]
    waiting_branches = tree_dicts[1:]
    num_active = 1

    while num_active > 0:
        next_branch_data = random.choice(active_branches)
        if "branch" in next_branch_data:
            prev_hash = next_branch_data["branch"].tip.hash
        else:
            prev_hash = next_branch_data.pop("root hash")
        num_nodes += 1
        new_hash = dummy_hash(num_nodes)
        block_score = 1
        if "scores" in next_branch_data:
            if "branch" in next_branch_data:
                if len(next_branch_data["scores"]) > len(next_branch_data["branch"]):
                    block_score = next_branch_data["scores"][len(next_branch_data["branch"])]
            else:
                block_score = next_branch_data["scores"][0]
        tree.add_block(new_hash, prev_hash, block_score)
        extended_branch = tree.hash_to_branch_lookup[new_hash]
        next_branch_data.update({"branch": extended_branch})

        for branch_dict in waiting_branches:
            if branch_dict["parent"] == next_branch_data["branch number"]:
                if len(extended_branch) > branch_dict["root"] + 1:
                    branch_dict.update({"root hash": prev_hash})
                    active_branches.append(branch_dict)
                    waiting_branches.remove(branch_dict)
                    num_active += 1

        if len(extended_branch) >= next_branch_data["length"]:
            active_branches.remove(next_branch_data)
            num_active -= 1

    return tree


def generate_random_tree(
    num_nodes: int,
    branch_probability: float = 0.1,
    branch_range: int = 2,
    branch_end_prob=0.25,
    earliest_branch: int = 1,
):
    """Procedurally generates a random tree with the specified number of nodes. Each time a new 
    block is added, a branch among the active branches (which always include the trunk) is selected
    at random. The block is either added to the end of that branch or (with probability defined by
    branch_probability param), added as the start of a child branch of that branch, at a random 
    location. To ensure that the trunk is overall the dominant branch, each branch has a chance of 
    becoming inactive each time a block is added, at which point it will never be extended (though 
    its children might).

    Args:
        num_nodes (int): how many BlockNodes will be added to the tree in total
        branch_probability (float): the chance that a newly added block starts a new branch. 
            Increments of less than 0.01 do nothing in practice.
        branch_range (int): controls how far back along the parent branch a new branch is likely to 
            form. Probability is a falling exponential: there's a 50% chance of a branch forming in
            the first branch_range blocks, a 25% in the next branch_range blocks and so on.
        branch_end_prob (float): Chance that a branch will become inactive each time a block is 
            added to it. This keeps the number of branches from growing too large.
        earlest_branch (int): Lowest index a child branch can appear on a parent branch.
    """

    tree = BlockScoreTree()

    prev_hash = None
    active_branches = [tree.trunk]
    for i in range(num_nodes):
        node_hash = dummy_hash(i)
        active_branch_roll = random.randint(0, len(active_branches) - 1)
        active_branch = active_branches[active_branch_roll]
        unbranched = True
        if len(active_branch) > earliest_branch:
            branch_roll = random.randint(1, 100)
            if branch_roll < branch_probability * 100:
                unbranched = False
        if not unbranched:  # Find where to start the new branch
            pred_idx = -len(active_branch)
            while len(active_branch) + pred_idx < earliest_branch:
                branch_loc_roll = random.randint(1, 2**10 - 1)
                pred_idx = -math.ceil(branch_range * (10 - math.log2(branch_loc_roll)))
        else:
            pred_idx = -1

        if len(active_branch) > 0:
            prev_hash = active_branch[pred_idx].hash
        else:
            prev_hash = None

        tree.add_block(block_hash=node_hash, prev_block_hash=prev_hash, block_score=1.0)

        if not unbranched:
            new_branch = tree.branches[-1]
            active_branches.append(new_branch)

        if active_branch_roll > 0:
            branch_end_roll = random.randint(1, 100)
            if branch_end_roll < branch_end_prob * 100:
                active_branches.pop(active_branch_roll)

    return tree
